version: '3.7'
services:
  # -------------------- infrastructure
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: swa-tp-nginx
    ports:
      - 80:80
    depends_on:
      - user-service
      - swagger-ui

  swagger-ui:
    build:
      context: swagger-ui
      dockerfile: Dockerfile
    image: swa-tp-swagger-ui

  # -------------------- user service
  user-service:
    image: lukaswire/swa-user-service
    env_file:
      - envs/common.env
      - envs/user-service.env
    depends_on:
      - user-service-db

  user-service-db:
    image: postgres:12.2
    env_file:
      - envs/user-service.env
    volumes:
      - swa-user-service-db-vol:/var/lib/postgresql/data/

  # -------------------- other services
volumes:
  swa-user-service-db-vol: